//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.FFXIVTranslate.localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACT.FFXIVTranslate.localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 FF14 消息翻译 的本地化字符串。
        /// </summary>
        public static string actPanelTitle {
            get {
                return ResourceManager.GetString("actPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        public static string buttonCheckUpdate {
            get {
                return ResourceManager.GetString("buttonCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开下载页面 的本地化字符串。
        /// </summary>
        public static string buttonDownloadUpdate {
            get {
                return ResourceManager.GetString("buttonDownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改字体 的本地化字符串。
        /// </summary>
        public static string buttonFont {
            get {
                return ResourceManager.GetString("buttonFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用公用密钥 的本地化字符串。
        /// </summary>
        public static string buttonFreeKey {
            get {
                return ResourceManager.GetString("buttonFreeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略 的本地化字符串。
        /// </summary>
        public static string buttonIgnoreVersion {
            get {
                return ResourceManager.GetString("buttonIgnoreVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 的本地化字符串。
        /// </summary>
        public static string buttonProviderApply {
            get {
                return ResourceManager.GetString("buttonProviderApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 的本地化字符串。
        /// </summary>
        public static string buttonProxyApply {
            get {
                return ResourceManager.GetString("buttonProxyApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从游戏中读取配色 的本地化字符串。
        /// </summary>
        public static string buttonReadColor {
            get {
                return ResourceManager.GetString("buttonReadColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稍后 的本地化字符串。
        /// </summary>
        public static string buttonUpdateLater {
            get {
                return ResourceManager.GetString("buttonUpdateLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string buttonUpdateNow {
            get {
                return ResourceManager.GetString("buttonUpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 24小时制 的本地化字符串。
        /// </summary>
        public static string checkBox24Hour {
            get {
                return ResourceManager.GetString("checkBox24Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示消息时间戳 的本地化字符串。
        /// </summary>
        public static string checkBoxAddTimestamp {
            get {
                return ResourceManager.GetString("checkBoxAddTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 悬浮窗自动隐藏 的本地化字符串。
        /// </summary>
        public static string checkBoxAutoHide {
            get {
                return ResourceManager.GetString("checkBoxAutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 团队 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterAlliance {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterAlliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部队 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterFC {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯贝1 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterLS1 {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterLS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯贝2 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterLS2 {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterLS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯贝3 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterLS3 {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterLS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯贝4 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterLS4 {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterLS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯贝5 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterLS5 {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterLS5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯贝6 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterLS6 {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterLS6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯贝7 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterLS7 {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterLS7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯贝8 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterLS8 {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterLS8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新人频道 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterNovice {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterNovice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非玩家角色对话 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterNPC {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterNPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小队 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterParty {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说话 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterSay {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 喊话 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterShout {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterShout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 悄悄话 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterTell {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterTell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呼喊 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterYell {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterYell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动检查更新 的本地化字符串。
        /// </summary>
        public static string checkBoxCheckUpdate {
            get {
                return ResourceManager.GetString("checkBoxCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标穿透 的本地化字符串。
        /// </summary>
        public static string checkBoxClickthrough {
            get {
                return ResourceManager.GetString("checkBoxClickthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只提示稳定版更新 的本地化字符串。
        /// </summary>
        public static string checkBoxNotifyStableOnly {
            get {
                return ResourceManager.GetString("checkBoxNotifyStableOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示悬浮窗 的本地化字符串。
        /// </summary>
        public static string checkBoxShowOverlay {
            get {
                return ResourceManager.GetString("checkBoxShowOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色数据读取完成！共设置了{0}个颜色。 的本地化字符串。
        /// </summary>
        public static string colorReadFinished {
            get {
                return ResourceManager.GetString("colorReadFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将会覆写已经存在的设置，是否要继续？ 的本地化字符串。
        /// </summary>
        public static string configOverwriteConfirm {
            get {
                return ResourceManager.GetString("configOverwriteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 悬浮窗设置 的本地化字符串。
        /// </summary>
        public static string groupBoxOverlay {
            get {
                return ResourceManager.GetString("groupBoxOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻译来源设置 的本地化字符串。
        /// </summary>
        public static string groupBoxProvider {
            get {
                return ResourceManager.GetString("groupBoxProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理设置 的本地化字符串。
        /// </summary>
        public static string groupBoxProxy {
            get {
                return ResourceManager.GetString("groupBoxProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件更新 的本地化字符串。
        /// </summary>
        public static string groupBoxUpdate {
            get {
                return ResourceManager.GetString("groupBoxUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API密钥: 的本地化字符串。
        /// </summary>
        public static string labelApiKey {
            get {
                return ResourceManager.GetString("labelApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频道颜色 的本地化字符串。
        /// </summary>
        public static string labelChannelColor {
            get {
                return ResourceManager.GetString("labelChannelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频道过滤 的本地化字符串。
        /// </summary>
        public static string labelChannelFilter {
            get {
                return ResourceManager.GetString("labelChannelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示频道标签 的本地化字符串。
        /// </summary>
        public static string labelChannelLabel {
            get {
                return ResourceManager.GetString("labelChannelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本: 的本地化字符串。
        /// </summary>
        public static string labelCurrentVersion {
            get {
                return ResourceManager.GetString("labelCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高: 的本地化字符串。
        /// </summary>
        public static string labelHeight {
            get {
                return ResourceManager.GetString("labelHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻译语言 的本地化字符串。
        /// </summary>
        public static string labelLang {
            get {
                return ResourceManager.GetString("labelLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源语言: 的本地化字符串。
        /// </summary>
        public static string labelLangFrom {
            get {
                return ResourceManager.GetString("labelLangFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标语言: 的本地化字符串。
        /// </summary>
        public static string labelLangTo {
            get {
                return ResourceManager.GetString("labelLangTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新稳定版本: 的本地化字符串。
        /// </summary>
        public static string labelLatestStableVersion {
            get {
                return ResourceManager.GetString("labelLatestStableVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新版本: 的本地化字符串。
        /// </summary>
        public static string labelLatestVersion {
            get {
                return ResourceManager.GetString("labelLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言: 的本地化字符串。
        /// </summary>
        public static string labelMainLanguage {
            get {
                return ResourceManager.GetString("labelMainLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *需要重启ACT。 的本地化字符串。
        /// </summary>
        public static string labelNeedToRestart {
            get {
                return ResourceManager.GetString("labelNeedToRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不透明度: 的本地化字符串。
        /// </summary>
        public static string labelOpacity {
            get {
                return ResourceManager.GetString("labelOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置 的本地化字符串。
        /// </summary>
        public static string labelPosition {
            get {
                return ResourceManager.GetString("labelPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来源: 的本地化字符串。
        /// </summary>
        public static string labelProvider {
            get {
                return ResourceManager.GetString("labelProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 域: 的本地化字符串。
        /// </summary>
        public static string labelProxyDomain {
            get {
                return ResourceManager.GetString("labelProxyDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码: 的本地化字符串。
        /// </summary>
        public static string labelProxyPassword {
            get {
                return ResourceManager.GetString("labelProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口: 的本地化字符串。
        /// </summary>
        public static string labelProxyPort {
            get {
                return ResourceManager.GetString("labelProxyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器: 的本地化字符串。
        /// </summary>
        public static string labelProxyServer {
            get {
                return ResourceManager.GetString("labelProxyServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型: 的本地化字符串。
        /// </summary>
        public static string labelProxyType {
            get {
                return ResourceManager.GetString("labelProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名: 的本地化字符串。
        /// </summary>
        public static string labelProxyUser {
            get {
                return ResourceManager.GetString("labelProxyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尺寸 的本地化字符串。
        /// </summary>
        public static string labelSize {
            get {
                return ResourceManager.GetString("labelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽: 的本地化字符串。
        /// </summary>
        public static string labelWidth {
            get {
                return ResourceManager.GetString("labelWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动检测 的本地化字符串。
        /// </summary>
        public static string LangAutoDetect {
            get {
                return ResourceManager.GetString("LangAutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前已是最新版！ 的本地化字符串。
        /// </summary>
        public static string messageLatest {
            get {
                return ResourceManager.GetString("messageLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新的抢鲜版: {0}。 的本地化字符串。
        /// </summary>
        public static string messageNewPrerelease {
            get {
                return ResourceManager.GetString("messageNewPrerelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新的稳定版: {0}。 的本地化字符串。
        /// </summary>
        public static string messageNewStable {
            get {
                return ResourceManager.GetString("messageNewStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该翻译来源未提供公用密钥。请参照插件文档获取密钥。 的本地化字符串。
        /// </summary>
        public static string messageNoFreeKey {
            get {
                return ResourceManager.GetString("messageNoFreeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置读取失败！
        ///{0} 的本地化字符串。
        /// </summary>
        public static string messageSettingsReadFailed {
            get {
                return ResourceManager.GetString("messageSettingsReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择了错误的文件夹！ 的本地化字符串。
        /// </summary>
        public static string messageWrongDir {
            get {
                return ResourceManager.GetString("messageWrongDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择最终幻想14用户设置文件夹。
        ///通常位于 我的文档\\My Games\\FINAL FANTASY XIV - A Realm Reborn 并且以 FFXIV_CHR 开头。 的本地化字符串。
        /// </summary>
        public static string openGameConfigDescription {
            get {
                return ResourceManager.GetString("openGameConfigDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTTP代理 的本地化字符串。
        /// </summary>
        public static string proxyTypeHttp {
            get {
                return ResourceManager.GetString("proxyTypeHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不使用代理 的本地化字符串。
        /// </summary>
        public static string proxyTypeNone {
            get {
                return ResourceManager.GetString("proxyTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SOCKS5代理 的本地化字符串。
        /// </summary>
        public static string proxyTypeSocks5 {
            get {
                return ResourceManager.GetString("proxyTypeSocks5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频道设置 的本地化字符串。
        /// </summary>
        public static string tabPageChannelSettings {
            get {
                return ResourceManager.GetString("tabPageChannelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规设置 的本地化字符串。
        /// </summary>
        public static string tabPageGeneralSettings {
            get {
                return ResourceManager.GetString("tabPageGeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件日志 的本地化字符串。
        /// </summary>
        public static string tabPageLog {
            get {
                return ResourceManager.GetString("tabPageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;上午 &quot;h:MM 的本地化字符串。
        /// </summary>
        public static string timeFormat12HourAM {
            get {
                return ResourceManager.GetString("timeFormat12HourAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;下午 &quot;h:MM 的本地化字符串。
        /// </summary>
        public static string timeFormat12HourPM {
            get {
                return ResourceManager.GetString("timeFormat12HourPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查中... 的本地化字符串。
        /// </summary>
        public static string updateChecking {
            get {
                return ResourceManager.GetString("updateChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        public static string versionUnknown {
            get {
                return ResourceManager.GetString("versionUnknown", resourceCulture);
            }
        }
    }
}
