//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.FFXIVTranslate.localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACT.FFXIVTranslate.localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 FF14 消息翻译 的本地化字符串。
        /// </summary>
        public static string actPanelTitle {
            get {
                return ResourceManager.GetString("actPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改字体 的本地化字符串。
        /// </summary>
        public static string buttonFont {
            get {
                return ResourceManager.GetString("buttonFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用公用密钥 的本地化字符串。
        /// </summary>
        public static string buttonFreeKey {
            get {
                return ResourceManager.GetString("buttonFreeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 的本地化字符串。
        /// </summary>
        public static string buttonProviderApply {
            get {
                return ResourceManager.GetString("buttonProviderApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 团队 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterAlliance {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterAlliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部队 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterFC {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯贝1 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterLS1 {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterLS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯贝2 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterLS2 {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterLS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯贝3 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterLS3 {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterLS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯贝4 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterLS4 {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterLS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯贝5 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterLS5 {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterLS5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯贝6 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterLS6 {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterLS6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯贝7 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterLS7 {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterLS7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯贝8 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterLS8 {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterLS8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新人频道 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterNovice {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterNovice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小队 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterParty {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 说话 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterSay {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 喊话 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterShout {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterShout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 悄悄话 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterTell {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterTell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呼喊 的本地化字符串。
        /// </summary>
        public static string checkBoxChannelFilterYell {
            get {
                return ResourceManager.GetString("checkBoxChannelFilterYell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标穿透 的本地化字符串。
        /// </summary>
        public static string checkBoxClickthrough {
            get {
                return ResourceManager.GetString("checkBoxClickthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 频道过滤 的本地化字符串。
        /// </summary>
        public static string groupBoxChannelFilter {
            get {
                return ResourceManager.GetString("groupBoxChannelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 悬浮窗设置 的本地化字符串。
        /// </summary>
        public static string groupBoxOverlay {
            get {
                return ResourceManager.GetString("groupBoxOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻译来源设置 的本地化字符串。
        /// </summary>
        public static string groupBoxProvider {
            get {
                return ResourceManager.GetString("groupBoxProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API密钥: 的本地化字符串。
        /// </summary>
        public static string labelApiKey {
            get {
                return ResourceManager.GetString("labelApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高: 的本地化字符串。
        /// </summary>
        public static string labelHeight {
            get {
                return ResourceManager.GetString("labelHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻译语言 的本地化字符串。
        /// </summary>
        public static string labelLang {
            get {
                return ResourceManager.GetString("labelLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源语言: 的本地化字符串。
        /// </summary>
        public static string labelLangFrom {
            get {
                return ResourceManager.GetString("labelLangFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标语言: 的本地化字符串。
        /// </summary>
        public static string labelLangTo {
            get {
                return ResourceManager.GetString("labelLangTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言: 的本地化字符串。
        /// </summary>
        public static string labelMainLanguage {
            get {
                return ResourceManager.GetString("labelMainLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *需要重启ACT。 的本地化字符串。
        /// </summary>
        public static string labelNeedToRestart {
            get {
                return ResourceManager.GetString("labelNeedToRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 透明度: 的本地化字符串。
        /// </summary>
        public static string labelOpacity {
            get {
                return ResourceManager.GetString("labelOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置 的本地化字符串。
        /// </summary>
        public static string labelPosition {
            get {
                return ResourceManager.GetString("labelPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来源: 的本地化字符串。
        /// </summary>
        public static string labelProvider {
            get {
                return ResourceManager.GetString("labelProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尺寸 的本地化字符串。
        /// </summary>
        public static string labelSize {
            get {
                return ResourceManager.GetString("labelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽: 的本地化字符串。
        /// </summary>
        public static string labelWidth {
            get {
                return ResourceManager.GetString("labelWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动检测 的本地化字符串。
        /// </summary>
        public static string LangAutoDetect {
            get {
                return ResourceManager.GetString("LangAutoDetect", resourceCulture);
            }
        }
    }
}
